language: php

sudo: false

dist: trusty

matrix:
  include:
   - php: 7.2
   - php: 7.3
   - php: 7.4
#   - php: nightly # PHP nightly build testing disabled because PHPUnit doesn't support PHP8 yet.
  fast_finish: true
  allow_failures:
   - php: nightly

services:
  - memcached
  - mysql

before_script:
    - mysql -e "create database IF NOT EXISTS test;" -uroot

before_install:
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install

script:
   - ./phpunit.sh
